### GOODLUCK ###
POST https://vmsprison.azurewebsites.net/register
Content-Type: application/json

{
  "username": "jim",
  "password": "123"
}

###
POST https://vmsprison.azurewebsites.net/login
Content-Type: application/json

{
  "username": "jim",
  "password": "123"
}
###

###
POST https://vmsprison.azurewebsites.net/createvisitorData
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0

{
    "name": "Sarah Jose",
    "city": "Melbourne",
    "relationship": "aunt",
    "visitorId": "008"
  
}
###


GET http://localhost:3000/admins
Content-Type: application/json
###

GET https://vmsprison.azurewebsites.net/visitor
Content-Type: application/json
###

GET https://vmsprison.azurewebsites.net/prisoner
Content-Type: application/json
###

GET http://localhost:3000/cell
Content-Type: application/json
###

GET http://localhost:3000/emergency
Content-Type: application/json
###

GET http://localhost:3000/casedetail
Content-Type: application/json
###